# Generated by Django 3.0.6 on 2020-05-31 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(max_length=32)),
                ('col', models.IntegerField(default=0)),
                ('row', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('inside_grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_components.Components')),
            ],
        ),
        migrations.CreateModel(
            name='settings_row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=64)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_components.Components')),
            ],
        ),
    ]
