# Generated by Django 3.2.5 on 2021-08-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_components', '0002_resume_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='resume',
        ),
    ]
