# Generated by Django 3.0.6 on 2020-05-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_components', '0003_auto_20200531_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.CharField(choices=[('C_CARD', 'Card Component')], max_length=32),
        ),
    ]
