# Generated by Django 3.0.6 on 2020-05-31 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_components', '0004_auto_20200531_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameField(
            model_name='component',
            old_name='inside_grid',
            new_name='inside_component',
        ),
        migrations.AlterField(
            model_name='component',
            name='col',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='component',
            name='height',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='component',
            name='row',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='component',
            name='width',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='settingsrow',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume_components.Component'),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num', models.IntegerField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_components.Resume')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='inside_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume_components.Page'),
        ),
        migrations.AddField(
            model_name='settingsrow',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume_components.Page'),
        ),
        migrations.AddField(
            model_name='settingsrow',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume_components.Resume'),
        ),
    ]
