# Generated by Django 3.0.6 on 2020-05-31 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_components', '0005_auto_20200531_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='inside_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_components', to='resume_components.Component'),
        ),
        migrations.AlterField(
            model_name='component',
            name='inside_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_components', to='resume_components.Page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='resume_components.Resume'),
        ),
        migrations.AlterField(
            model_name='settingsrow',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='resume_components.Component'),
        ),
        migrations.AlterField(
            model_name='settingsrow',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='resume_components.Page'),
        ),
        migrations.AlterField(
            model_name='settingsrow',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='resume_components.Resume'),
        ),
    ]
