# Generated by Django 3.0.6 on 2020-05-31 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_components', '0006_auto_20200531_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='resume_components.Resume'),
            preserve_default=False,
        ),
    ]
