# Generated by Django 3.2.5 on 2021-08-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_components', '0007_alter_component_component_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.CharField(choices=[('E_CARD', 'Card Experience'), ('C_COL_A', 'Colored Area'), ('C_T_COL_A', 'Themed Colored Area'), ('T_TYP', 'Typography Text'), ('T_T_TYP', 'Themed Typography Text'), ('O_IM', 'Image')], max_length=32),
        ),
    ]
