# Generated by Django 3.2.5 on 2021-08-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_components', '0008_alter_component_component_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsrow',
            name='setting',
            field=models.CharField(max_length=256),
        ),
    ]
