# Generated by Django 3.2.5 on 2021-08-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_components', '0009_alter_settingsrow_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsrow',
            name='setting',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='settingsrow',
            name='value',
            field=models.CharField(max_length=256),
        ),
    ]
