# docker-compose.yml

version: '3.9'

services:
  backend:
    build: ./material-resume-backend
    volumes:
      - ./material-resume-backend:/usr/src/app
    expose:
      - 8000

  frontend:
    stdin_open: true
    build: ./material-resume-frontend
    volumes:
      - ./material-resume-frontend:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - 3000
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  pdf_generator:
    stdin_open: true
    build: ./material-resume-pdf-generator
    restart: on-failure
    volumes:
      - ./material-resume-pdf-generator:/usr/src/app
    security_opt:
      - seccomp=./.chrome.json
    expose:
      - 3001

  reverse_proxy:
    build: ./nginx
    ports:
      - 81:80
    depends_on:
      - backend
      - frontend
      - pdf_generator
