import React from 'react';

export const languages = [
    {"abrv":"en","text":"English","nativeName":"English"},
    {"abrv":"sv","text":"Swedish","nativeName":"svenska"},
    {"abrv":"de","text":"German","nativeName":"Deutsch"},
    {"abrv":"es","text":"Spanish; Castilian","nativeName":"español, castellano"},
    {"abrv":"ab","text":"Abkhaz","nativeName":"аҧсуа"},
    {"abrv":"aa","text":"Afar","nativeName":"Afaraf"},
    {"abrv":"af","text":"Afrikaans","nativeName":"Afrikaans"},
    {"abrv":"ak","text":"Akan","nativeName":"Akan"},
    {"abrv":"sq","text":"Albanian","nativeName":"Shqip"},
    {"abrv":"am","text":"Amharic","nativeName":"አማርኛ"},
    {"abrv":"ar","text":"Arabic","nativeName":"العربية"},
    {"abrv":"an","text":"Aragonese","nativeName":"Aragonés"},
    {"abrv":"hy","text":"Armenian","nativeName":"Հայերեն"},
    {"abrv":"as","text":"Assamese","nativeName":"অসমীয়া"},
    {"abrv":"av","text":"Avaric","nativeName":"авар мацӀ, магӀарул мацӀ"},
    {"abrv":"ae","text":"Avestan","nativeName":"avesta"},
    {"abrv":"ay","text":"Aymara","nativeName":"aymar aru"},
    {"abrv":"az","text":"Azerbaijani","nativeName":"azərbaycan dili"},
    {"abrv":"bm","text":"Bambara","nativeName":"bamanankan"},
    {"abrv":"ba","text":"Bashkir","nativeName":"башҡорт теле"},
    {"abrv":"eu","text":"Basque","nativeName":"euskara, euskera"},
    {"abrv":"be","text":"Belarusian","nativeName":"Беларуская"},
    {"abrv":"bn","text":"Bengali","nativeName":"বাংলা"},
    {"abrv":"bh","text":"Bihari","nativeName":"भोजपुरी"},
    {"abrv":"bi","text":"Bislama","nativeName":"Bislama"},
    {"abrv":"bs","text":"Bosnian","nativeName":"bosanski jezik"},
    {"abrv":"br","text":"Breton","nativeName":"brezhoneg"},
    {"abrv":"bg","text":"Bulgarian","nativeName":"български език"},
    {"abrv":"my","text":"Burmese","nativeName":"ဗမာစာ"},
    {"abrv":"ca","text":"Catalan; Valencian","nativeName":"Català"},
    {"abrv":"ch","text":"Chamorro","nativeName":"Chamoru"},
    {"abrv":"ce","text":"Chechen","nativeName":"нохчийн мотт"},
    {"abrv":"ny","text":"Chichewa; Chewa; Nyanja","nativeName":"chiCheŵa, chinyanja"},
    {"abrv":"zh","text":"Chinese","nativeName":"中文 (Zhōngwén), 汉语, 漢語"},
    {"abrv":"cv","text":"Chuvash","nativeName":"чӑваш чӗлхи"},
    {"abrv":"kw","text":"Cornish","nativeName":"Kernewek"},
    {"abrv":"co","text":"Corsican","nativeName":"corsu, lingua corsa"},
    {"abrv":"cr","text":"Cree","nativeName":"ᓀᐦᐃᔭᐍᐏᐣ"},
    {"abrv":"hr","text":"Croatian","nativeName":"hrvatski"},
    {"abrv":"cs","text":"Czech","nativeName":"česky, čeština"},
    {"abrv":"da","text":"Danish","nativeName":"dansk"},
    {"abrv":"dv","text":"Divehi; Dhivehi; Maldivian;","nativeName":"ދިވެހި"},
    {"abrv":"nl","text":"Dutch","nativeName":"Nederlands, Vlaams"},
    {"abrv":"eo","text":"Esperanto","nativeName":"Esperanto"},
    {"abrv":"et","text":"Estonian","nativeName":"eesti, eesti keel"},
    {"abrv":"ee","text":"Ewe","nativeName":"Eʋegbe"},
    {"abrv":"fo","text":"Faroese","nativeName":"føroyskt"},
    {"abrv":"fj","text":"Fijian","nativeName":"vosa Vakaviti"},
    {"abrv":"fi","text":"Finnish","nativeName":"suomi, suomen kieli"},
    {"abrv":"fr","text":"French","nativeName":"français, langue française"},
    {"abrv":"ff","text":"Fula; Fulah; Pulaar; Pular","nativeName":"Fulfulde, Pulaar, Pular"},
    {"abrv":"gl","text":"Galician","nativeName":"Galego"},
    {"abrv":"ka","text":"Georgian","nativeName":"ქართული"},
    {"abrv":"el","text":"Greek, Modern","nativeName":"Ελληνικά"},
    {"abrv":"gn","text":"Guaraní","nativeName":"Avañeẽ"},
    {"abrv":"gu","text":"Gujarati","nativeName":"ગુજરાતી"},
    {"abrv":"ht","text":"Haitian; Haitian Creole","nativeName":"Kreyòl ayisyen"},
    {"abrv":"ha","text":"Hausa","nativeName":"Hausa, هَوُسَ"},
    {"abrv":"he","text":"Hebrew (modern)","nativeName":"עברית"},
    {"abrv":"hz","text":"Herero","nativeName":"Otjiherero"},
    {"abrv":"hi","text":"Hindi","nativeName":"हिन्दी, हिंदी"},
    {"abrv":"ho","text":"Hiri Motu","nativeName":"Hiri Motu"},
    {"abrv":"hu","text":"Hungarian","nativeName":"Magyar"},
    {"abrv":"ia","text":"Interlingua","nativeName":"Interlingua"},
    {"abrv":"id","text":"Indonesian","nativeName":"Bahasa Indonesia"},
    {"abrv":"ie","text":"Interlingue","nativeName":"Originally called Occidental; then Interlingue after WWII"},
    {"abrv":"ga","text":"Irish","nativeName":"Gaeilge"},
    {"abrv":"ig","text":"Igbo","nativeName":"Asụsụ Igbo"},
    {"abrv":"ik","text":"Inupiaq","nativeName":"Iñupiaq, Iñupiatun"},
    {"abrv":"io","text":"Ido","nativeName":"Ido"},
    {"abrv":"is","text":"Icelandic","nativeName":"Íslenska"},
    {"abrv":"it","text":"Italian","nativeName":"Italiano"},
    {"abrv":"iu","text":"Inuktitut","nativeName":"ᐃᓄᒃᑎᑐᑦ"},
    {"abrv":"ja","text":"Japanese","nativeName":"日本語 (にほんご／にっぽんご)"},
    {"abrv":"jv","text":"Javanese","nativeName":"basa Jawa"},
    {"abrv":"kl","text":"Kalaallisut, Greenlandic","nativeName":"kalaallisut, kalaallit oqaasii"},
    {"abrv":"kn","text":"Kannada","nativeName":"ಕನ್ನಡ"},
    {"abrv":"kr","text":"Kanuri","nativeName":"Kanuri"},
    {"abrv":"ks","text":"Kashmiri","nativeName":"कश्मीरी, كشميري‎"},
    {"abrv":"kk","text":"Kazakh","nativeName":"Қазақ тілі"},
    {"abrv":"km","text":"Khmer","nativeName":"ភាសាខ្មែរ"},
    {"abrv":"ki","text":"Kikuyu, Gikuyu","nativeName":"Gĩkũyũ"},
    {"abrv":"rw","text":"Kinyarwanda","nativeName":"Ikinyarwanda"},
    {"abrv":"ky","text":"Kirghiz, Kyrgyz","nativeName":"кыргыз тили"},
    {"abrv":"kv","text":"Komi","nativeName":"коми кыв"},
    {"abrv":"kg","text":"Kongo","nativeName":"KiKongo"},
    {"abrv":"ko","text":"Korean","nativeName":"한국어 (韓國語), 조선말 (朝鮮語)"},
    {"abrv":"ku","text":"Kurdish","nativeName":"Kurdî, كوردی‎"},
    {"abrv":"kj","text":"Kwanyama, Kuanyama","nativeName":"Kuanyama"},
    {"abrv":"la","text":"Latin","nativeName":"latine, lingua latina"},
    {"abrv":"lb","text":"Luxembourgish, Letzeburgesch","nativeName":"Lëtzebuergesch"},
    {"abrv":"lg","text":"Luganda","nativeName":"Luganda"},
    {"abrv":"li","text":"Limburgish, Limburgan, Limburger","nativeName":"Limburgs"},
    {"abrv":"ln","text":"Lingala","nativeName":"Lingála"},
    {"abrv":"lo","text":"Lao","nativeName":"ພາສາລາວ"},
    {"abrv":"lt","text":"Lithuanian","nativeName":"lietuvių kalba"},
    {"abrv":"lu","text":"Luba-Katanga","nativeName":""},
    {"abrv":"lv","text":"Latvian","nativeName":"latviešu valoda"},
    {"abrv":"gv","text":"Manx","nativeName":"Gaelg, Gailck"},
    {"abrv":"mk","text":"Macedonian","nativeName":"македонски јазик"},
    {"abrv":"mg","text":"Malagasy","nativeName":"Malagasy fiteny"},
    {"abrv":"ms","text":"Malay","nativeName":"bahasa Melayu, بهاس ملايو‎"},
    {"abrv":"ml","text":"Malayalam","nativeName":"മലയാളം"},
    {"abrv":"mt","text":"Maltese","nativeName":"Malti"},
    {"abrv":"mi","text":"Māori","nativeName":"te reo Māori"},
    {"abrv":"mr","text":"Marathi (Marāṭhī)","nativeName":"मराठी"},
    {"abrv":"mh","text":"Marshallese","nativeName":"Kajin M̧ajeļ"},
    {"abrv":"mn","text":"Mongolian","nativeName":"монгол"},
    {"abrv":"na","text":"Nauru","nativeName":"Ekakairũ Naoero"},
    {"abrv":"nv","text":"Navajo, Navaho","nativeName":"Diné bizaad, Dinékʼehǰí"},
    {"abrv":"nb","text":"Norwegian Bokmål","nativeName":"Norsk bokmål"},
    {"abrv":"nd","text":"North Ndebele","nativeName":"isiNdebele"},
    {"abrv":"ne","text":"Nepali","nativeName":"नेपाली"},
    {"abrv":"ng","text":"Ndonga","nativeName":"Owambo"},
    {"abrv":"nn","text":"Norwegian Nynorsk","nativeName":"Norsk nynorsk"},
    {"abrv":"no","text":"Norwegian","nativeName":"Norsk"},
    {"abrv":"ii","text":"Nuosu","nativeName":"ꆈꌠ꒿ Nuosuhxop"},
    {"abrv":"nr","text":"South Ndebele","nativeName":"isiNdebele"},
    {"abrv":"oc","text":"Occitan","nativeName":"Occitan"},
    {"abrv":"oj","text":"Ojibwe, Ojibwa","nativeName":"ᐊᓂᔑᓈᐯᒧᐎᓐ"},
    {"abrv":"cu","text":"Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic","nativeName":"ѩзыкъ словѣньскъ"},
    {"abrv":"om","text":"Oromo","nativeName":"Afaan Oromoo"},
    {"abrv":"or","text":"Oriya","nativeName":"ଓଡ଼ିଆ"},
    {"abrv":"os","text":"Ossetian, Ossetic","nativeName":"ирон æвзаг"},
    {"abrv":"pa","text":"Panjabi, Punjabi","nativeName":"ਪੰਜਾਬੀ, پنجابی‎"},
    {"abrv":"pi","text":"Pāli","nativeName":"पाऴि"},
    {"abrv":"fa","text":"Persian","nativeName":"فارسی"},
    {"abrv":"pl","text":"Polish","nativeName":"polski"},
    {"abrv":"ps","text":"Pashto, Pushto","nativeName":"پښتو"},
    {"abrv":"pt","text":"Portuguese","nativeName":"Português"},
    {"abrv":"qu","text":"Quechua","nativeName":"Runa Simi, Kichwa"},
    {"abrv":"rm","text":"Romansh","nativeName":"rumantsch grischun"},
    {"abrv":"rn","text":"Kirundi","nativeName":"kiRundi"},
    {"abrv":"ro","text":"Romanian, Moldavian, Moldovan","nativeName":"română"},
    {"abrv":"ru","text":"Russian","nativeName":"русский язык"},
    {"abrv":"sa","text":"Sanskrit (Saṁskṛta)","nativeName":"संस्कृतम्"},
    {"abrv":"sc","text":"Sardinian","nativeName":"sardu"},
    {"abrv":"sd","text":"Sindhi","nativeName":"सिन्धी, سنڌي، سندھی‎"},
    {"abrv":"se","text":"Northern Sami","nativeName":"Davvisámegiella"},
    {"abrv":"sm","text":"Samoan","nativeName":"gagana faa Samoa"},
    {"abrv":"sg","text":"Sango","nativeName":"yângâ tî sängö"},
    {"abrv":"sr","text":"Serbian","nativeName":"српски језик"},
    {"abrv":"gd","text":"Scottish Gaelic; Gaelic","nativeName":"Gàidhlig"},
    {"abrv":"sn","text":"Shona","nativeName":"chiShona"},
    {"abrv":"si","text":"Sinhala, Sinhalese","nativeName":"සිංහල"},
    {"abrv":"sk","text":"Slovak","nativeName":"slovenčina"},
    {"abrv":"sl","text":"Slovene","nativeName":"slovenščina"},
    {"abrv":"so","text":"Somali","nativeName":"Soomaaliga, af Soomaali"},
    {"abrv":"st","text":"Southern Sotho","nativeName":"Sesotho"},
    {"abrv":"su","text":"Sundanese","nativeName":"Basa Sunda"},
    {"abrv":"sw","text":"Swahili","nativeName":"Kiswahili"},
    {"abrv":"ss","text":"Swati","nativeName":"SiSwati"},
    {"abrv":"ta","text":"Tamil","nativeName":"தமிழ்"},
    {"abrv":"te","text":"Telugu","nativeName":"తెలుగు"},
    {"abrv":"tg","text":"Tajik","nativeName":"тоҷикӣ, toğikī, تاجیکی‎"},
    {"abrv":"th","text":"Thai","nativeName":"ไทย"},
    {"abrv":"ti","text":"Tigrinya","nativeName":"ትግርኛ"},
    {"abrv":"bo","text":"Tibetan Standard, Tibetan, Central","nativeName":"བོད་ཡིག"},
    {"abrv":"tk","text":"Turkmen","nativeName":"Türkmen, Түркмен"},
    {"abrv":"tl","text":"Tagalog","nativeName":"Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔"},
    {"abrv":"tn","text":"Tswana","nativeName":"Setswana"},
    {"abrv":"to","text":"Tonga (Tonga Islands)","nativeName":"faka Tonga"},
    {"abrv":"tr","text":"Turkish","nativeName":"Türkçe"},
    {"abrv":"ts","text":"Tsonga","nativeName":"Xitsonga"},
    {"abrv":"tt","text":"Tatar","nativeName":"татарча, tatarça, تاتارچا‎"},
    {"abrv":"tw","text":"Twi","nativeName":"Twi"},
    {"abrv":"ty","text":"Tahitian","nativeName":"Reo Tahiti"},
    {"abrv":"ug","text":"Uighur, Uyghur","nativeName":"Uyƣurqə, ئۇيغۇرچە‎"},
    {"abrv":"uk","text":"Ukrainian","nativeName":"українська"},
    {"abrv":"ur","text":"Urdu","nativeName":"اردو"},
    {"abrv":"uz","text":"Uzbek","nativeName":"zbek, Ўзбек, أۇزبېك‎"},
    {"abrv":"ve","text":"Venda","nativeName":"Tshivenḓa"},
    {"abrv":"vi","text":"Viettextse","nativeName":"Tiếng Việt"},
    {"abrv":"vo","text":"Volapük","nativeName":"Volapük"},
    {"abrv":"wa","text":"Walloon","nativeName":"Walon"},
    {"abrv":"cy","text":"Welsh","nativeName":"Cymraeg"},
    {"abrv":"wo","text":"Wolof","nativeName":"Wollof"},
    {"abrv":"fy","text":"Western Frisian","nativeName":"Frysk"},
    {"abrv":"xh","text":"Xhosa","nativeName":"isiXhosa"},
    {"abrv":"yi","text":"Yiddish","nativeName":"ייִדיש"},
    {"abrv":"yo","text":"Yoruba","nativeName":"Yorùbá"},
    {"abrv":"za","text":"Zhuang, Chuang","nativeName":"Saɯ cueŋƅ, Saw cuengh"}
]

export const languageList = languages.map(lang => {
  return({
    text: lang.text,
    abrv: lang.abrv,
    subtitle: lang.nativeName,
    icon: <img className='test1' alt="English" src={"https://unpkg.com/language-icons/icons/" + lang.abrv + ".svg"}/>
  })
})

export const abrvToLanguage = languageList.reduce((map, curVal) => {
  map[curVal.abrv] = curVal
  return map
}, {});
