# Generated by Django 3.2.5 on 2021-08-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_resume_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='settingOverrideTheme',
            field=models.BooleanField(default=False),
        ),
    ]
