# Generated by Django 3.2.5 on 2021-08-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_resume_backend', '0002_user_settingoverridetheme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='settingOverrideTheme',
            new_name='setting_override_theme',
        ),
    ]
