# Generated by Django 3.2.5 on 2021-08-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_resume_backend', '0003_rename_settingoverridetheme_user_setting_override_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='setting_page_theme',
            field=models.CharField(choices=[('THEME_BASELINE', 'Baseline'), ('THEME_CRANE', 'Crane'), ('THEME_DARK', 'Dark')], default='THEME_BASELINE', max_length=32),
            preserve_default=False,
        ),
    ]
