# Generated by Django 3.2.5 on 2021-08-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_resume_backend', '0004_user_setting_page_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='setting_page_theme',
            field=models.CharField(choices=[('THEME_BASELINE', 'Baseline'), ('THEME_CRANE', 'Crane'), ('THEME_DARK', 'Dark')], default='THEME_BASELINE', max_length=32),
        ),
    ]
