# Generated by Django 3.2.5 on 2021-11-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_resume_backend', '0006_auto_20211111_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=2),
        ),
    ]
