# Generated by Django 3.2.5 on 2021-07-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_entries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienceentry',
            name='end',
        ),
        migrations.RemoveField(
            model_name='experienceentry',
            name='start',
        ),
        migrations.AddField(
            model_name='experience',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
