# Generated by Django 3.2.5 on 2021-11-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_entries', '0002_auto_20210728_1146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
