# Generated by Django 3.0.6 on 2020-06-01 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume_entries', '0003_auto_20200601_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceentry',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experienceentry',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experienceentry',
            name='start',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='experienceentry',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
