# Generated by Django 3.2.5 on 2022-01-04 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material_resume_backend', '0007_alter_language_language'),
        ('resume_entries', '0003_delete_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceentry',
            name='lang_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='material_resume_backend.language'),
        ),
        migrations.AddField(
            model_name='textentry',
            name='lang_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='material_resume_backend.language'),
        ),
    ]
