# Generated by Django 3.0.6 on 2020-06-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_entries', '0004_auto_20200601_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experienceentry',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experienceentry',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experienceentry',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experienceentry',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
