# Generated by Django 3.0.6 on 2020-06-01 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_entries', '0005_auto_20200601_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='textentry',
            name='text_obj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='resume_entries.Text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textentry',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
