# Generated by Django 3.2.5 on 2022-01-04 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_entries', '0006_auto_20220104_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experienceentry',
            old_name='lang_id',
            new_name='lang',
        ),
        migrations.RenameField(
            model_name='textentry',
            old_name='lang_id',
            new_name='lang',
        ),
    ]
