# Generated by Django 3.2.5 on 2022-01-04 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material_resume_backend', '0007_alter_language_language'),
        ('resume_entries', '0007_auto_20220104_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceentry',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_resume_backend.language'),
        ),
        migrations.AlterField(
            model_name='textentry',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_resume_backend.language'),
        ),
    ]
